version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      # Install all dependencies (including dependencies for running tests)
      - python3 -m pip install boto3
  pre_build:
    commands:
      # TODO: unit test, other QA tools, etc
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
